<?php
$lang = array(
    "Refresh"=> "Оновити",
    "Add" => "Додати",
    "Urls" => "Посилання",
    "Name" => "Ім'я",
    "Data" => "Дата",
    "Size" => "Розмір",
    "Del" => "Вид",
    "Actual on" => "Актуально на",
    "Free" => "Вільно",
    "Home" => "На головну",
    "How to name it" => "Як назвати",
    "URL (https?://)" => "Адресса (https?://)",
    "Enable log" => "Вести лог",
    "Video ID" => "Відео ІД",
    "Video Name" => "Назва відео",
    "Choose quality" => "Виберіть якість",
    "Avitable quality" => "Доступні якості",
    "Selected quality" => "Вибран якість",
    "File name" => "Ім'я файлу",
    "ERROR" => "ПОМИЛКА",
    "Best" => "Краще",
    "DataTimeFormat" => "Y-m-d H:i:s",
    "From" => "з",
    "Loader" => "Завантажувач",
    "The name is not specified, the random name will be used" => "Не вказано ім'я, буде використано рандомне ім'я",
    "Error: There is already exist" => "Помилка: вже є такий файл",
    "Can not be deleted" => "Неможливо видалити",
    "does not exist" => "не існує",
    "Done" => "Готово",
    "Deleted" => "Видалено",
    "Welcome" => "Привіт",
    "Count" => "Всьго об'єктів: ",
	"download" => "Звантажити",
	"Busy" => "Зайнято"

 ); ?>

