<?php
$lang = array(
    "Refresh"=> "Refresh",
    "Add" => "Add",
    "Urls" => "Urls",
    "Name" => "Name",
    "Data" => "Data",
    "Size" => "Size",
    "Del" => "Del",
    "Actual on" => "Actual on",
    "Free" => "Free",
    "Home" => "Home",
    "How to name it" => "How to name it",
    "URL (https?://)" => "URL (https?://)",
    "Enable log" => "Enable log",
    "Video ID" => "Video ID",
    "Video Name" => "Video Name",
    "Choose quality" => "Choose quality",
    "Avitable quality" => "Avitable quality",
    "Selected quality" => "Selected quality",
    "File name" => "File name",
    "ERROR" => "ERROR",
    "Best" => "Best",
    "DataTimeFormat" => "Y-m-d H:i:s",
    "From" => "From",
    "Loader" => "Loader",
    "The name is not specified, the random name will be used" => "The name is not specified, the random name will be used",
    "Error: There is already exist" => "Error: There is already exist",
    "Can not be deleted" => "Can not be deleted",
    "does not exist" => "does not exist",
    "Done" => "Done",
    "Deleted" => "Deleted",
    "Welcome" => "Welcome"
);
?>
